---
# Configurações gerais
timezone: America/Sao_Paulo
locale: pt_BR.UTF-8

# Configurações de rede
# network_interface: ens18
# network_gateway: 192.168.31.1
# network_dns: 
#   - 8.8.8.8
#   - 1.1.1.1

# Configurações de usuário
# default_user: ubuntu
# default_group: ubuntu

# Configurações de segurança
# ssh_port: 22
# allowed_ssh_networks:
#   - 192.168.31.0/24
#   - 10.0.0.0/8

# # Configurações de sistema
# swappiness: 10
# max_open_files: 65535
# max_user_watches: 524288

# # Diretórios padrão
# base_dirs:
#   - /opt/apps
#   - /opt/data
#   - /opt/backups
#   - /opt/scripts

# # Configurações de proxy (se necessário)
# proxy_env:
#   http_proxy: ""
#   https_proxy: ""
#   no_proxy: "localhost,127.0.0.1"

# Configurações de pacotes
common_packages:
  - curl
  - wget
  - vim
  - git
  - htop
  - net-tools
  # - iptables-persistent
  # - python3-pip
  # - nfs-common

# Configurações de sysctl
# sysctl_settings:
#   net.ipv4.ip_forward: 1
#   net.bridge.bridge-nf-call-iptables: 1
#   vm.swappiness: "{{ swappiness }}"
#   fs.file-max: "{{ max_open_files }}"
#   fs.inotify.max_user_watches: "{{ max_user_watches }}"

# # Configurações de backup
# backup:
#   enabled: true
#   retention_days: 7
#   backup_dir: /opt/backups
#   exclude_dirs:
#     - /tmp
#     - /var/tmp
