---
# Versões dos componentes
k8s_version: "1.31.3"
containerd_version: "1.7.24"
runc_version: "1.2.2"
cni_plugins_version: "1.6.1"
calico_version: "3.29.1"
metallb_version: "0.13.12"

# Configurações de rede
pod_network_cidr: "10.10.0.0/16"
service_cidr: "10.96.0.0/12"
metallb_ip_range: "192.168.31.3-192.168.31.15"

# Configurações do HAProxy
haproxy_stats_port: 8404
haproxy_stats_user: "admin"
haproxy_stats_password: "admin"
k8s_api_port: 6443

# IPs dos nodes
haproxy_ip: "192.168.31.27"
master_ips:
  - "192.168.31.21"
  - "192.168.31.22"
  - "192.168.31.23"
worker_ips:
  - "192.168.31.24"
  - "192.168.31.25"
  - "192.168.31.26"

# Pacotes básicos
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg
  - wget
  - vim
  - git
  - htop
  - net-tools
  - iptables-persistent
  - python3-pip
  - nfs-common
