apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.17.2
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/diogofrj/proxmox-homelab/main/argocd/workloads/cert-manager/values-chart_1-17-2.yaml
      releaseName: cert-manager
  project: cloudseek
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  source:
    path: argocd/workloads/cert-manager
    repoURL: https://github.com/diogofrj/proxmox-homelab.git
    targetRevision: main
    directory:
      include: traefik-ingressroute.yaml
  project: cloudseek
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true